#ifndef TCPINTERACTION_GLOBAL_H
#define TCPINTERACTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TCPINTERACTION_LIBRARY)
#define TCPINTERACTION_EXPORT Q_DECL_EXPORT
#else
#define TCPINTERACTION_EXPORT Q_DECL_IMPORT
#endif

#endif // TCPINTERACTION_GLOBAL_H
